name: 'test-release'

on:
  push:
    branches:
      - release

jobs:
  publish-tauri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: setup Rust
        uses: dtolnay/rust-toolchain@stable
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: 'v1.0.0'
          releaseName: 'Test Release'
          releaseBody: 'Testing the release process'
          releaseDraft: false
          prerelease: false
